
import React from 'react';



const movies = [
    "Juno",
    "Bad Teacher",
    "What a Girl Wants",
    "Little Women",
    "Hairspray",
    "A Cinderella Story", 
    "Just Go With It", 
    "Baby Mama",
    "First Daughter",
    "Titanic", 
    "La La Land", 
    "Spy Kids",
    "The Great Gatsby", 
"Clueless",
"13 Going on 30", 
"Pride and Prejudice", 
"10 Things I Hate About You", 
"The House Bunny", 
"Cruel Intentions",
"Moulin Rouge ",
"Bring it On ",
"Love Actually ",
"Nick and Nora’s Infinite Playlist", 
"How to Lose a Guy in 10 Days", 
"The Princess Diaries", 
"She’s All That", 
"Legally Blonde", 
"Crazy Stupid Love", 
"Date Night", 
"Stick It", 
"What Happens in Vegas", 
"Heathers", 
"Across the Universe",
"Lizzie McGuire Movie", 
"Uptown Girls", 
"Aquamarine", 
"The Perfect Man", 
"Chicago",
"Sisterhood of the Traveling Pants", 
"Ella Enchanted", 
"The Greatest Showman", 
"Music and Lyrics", 
"Trainwreck", 
"Get Smart",
"First Daughter",
]
export default movies
